### ISSUE TITLE
Solus USB live doesn't boot in UEFI mode.

### ISSUE THREAD

**Issue by Nikki1993** [solus-project/os-installer#1]
Copy paste from G+ page :D 

Burned solus iso through dd command, specifically dd bs=4M if=SolusFTW.iso of=/dev/sdb && sync from arch wiki. Everything went fine and I was able to get uefi menu to start solus USB but that was pretty much it. After selecting solus it's just a blank screen. Nothing else. No output or anything like that. Tried installing it in dell xps 13 developer edition, 2013 version.

**Comment by Nikki1993** [comment]
Hardware:

CPU: Core i7-3537U 2.00 GHz
RAM: 8GB
PCI Devices-
Host bridge     : Intel Corporation 3rd Gen Core processor DRAM Controller (rev 09)
VGA compatible controller       : Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09) (prog-if 00 [VGA controller])
USB controller      : Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04) (prog-if 30 [XHCI])
Communication controller        : Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 (rev 04)
USB controller      : Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 (rev 04) (prog-if 20 [EHCI])
Audio device        : Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
PCI bridge      : Intel Corporation 7 Series/C210 Series Chipset Family PCI Express Root Port 1 (rev c4) (prog-if 00 [Normal decode])
USB controller      : Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 (rev 04) (prog-if 20 [EHCI])
ISA bridge      : Intel Corporation QS77 Express Chipset LPC Controller (rev 04)
SATA controller     : Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode](rev 04) (prog-if 01 [AHCI 1.0])
SMBus       : Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller (rev 04)
Network controller      : Intel Corporation Centrino Advanced-N 6235 (rev 24)

**Comment by freddyfernando** [comment]
Exact same issue. Solus wont go Live, and since there is no installer option I'm pretty much stuck. Tried booting from the BIOS rather than UEFI didn't work.
This seems to be the issue, but I cant get around it myself.
https://wiki.solus-project.com/UEFI
If you do find out how to do it share it with me..

**Comment by flukejones** [comment]
@FreddyFernando the Wiki article you link to is not the issue at all, that is only for installing.
It is basically down to syslinux (the iso boot loader for EFI); do this:
- Boot the ISO, then press 'e' on the boot entry
- Append `debug earlyprintk=efi,keep` to the end of the line
- Press F10 to boot

It will most likely be booting but previously without console output; with the options above it forces output to the console. Speed of booting is another question altogether.

For the record, this is also _not_ an issue with the installer at all.

**Comment by ikeydoherty** [comment]
Closing issue as this pertains to the USB3 issue in Solus 1.0, whereby XHCI module was split up in the kernel and caused boot failures. Was resolved in Solus 1.1
