### ISSUE TITLE
Finding your location screen bug

### ISSUE THREAD

**Issue by Quacky2200** [solus-project/os-installer#15]
'Finding your location' screen still shows up briefly (flickers) when the 'Find my location automatically' checkbox is not enabled.

See this video I put on YouTube: https://youtu.be/kf3lbqgBa_4
##

**Comment by ikeydoherty** [comment]
It's not a bug - you're using software rendering in a virtual machine so it's unable to keep a minimum FPS to render the animation from sliding across the pages where it deliberately skips that page.

**Comment by Quacky2200** [comment]
The page shouldn't even be rendered anyhow, it literally should not be inserted or 'skipped' unless I said I want the page to show up under the necessary options?

**Comment by ikeydoherty** [comment]
Pages aren't inserted dynamically, they exist before the questions are asked.

**Comment by ikeydoherty** [comment]
I'll see if `GtkStack` respects child visibility to omit it from the series
