### ISSUE TITLE
Installer Luks Support

### ISSUE THREAD

**Issue by stephenrjohnson** [solus-project/os-installer#19]
So I'm thinking about adding support encrypted installs and there are two ways of doing, 

1)
- EFI part, not encrypted 
- Encrypted  root partition password for encrypted swap part using luks
- Encrypted swap partition using luks

2)
- EFI part, not encrypted
- LVM on encrypted using luks
- LV for root, swap etc

Just wondering what peoples views are before I start working on it. 

(Setup for lvm and luks https://gist.github.com/jasonwryan/4618490)

**Comment by ikeydoherty** [comment]
We now support LVM on LUKS on whole-disk mode:

_UEFI:_
- ESP mandatory (`/boot/efi`)
- Single LUKS container
  - _maybe_ swap (depending on available space)
  - root (`/dev/SolusSystem/Root`)

_BIOS_:
- `/boot` mandatory, even if we don't install bootloader.
- Single LUKS container
  - _maybe_ swap (depending on available space)
  - root (`/dev/SolusSystem/Root`)

Considering a /home but I don't know yet, honestly.

I still have some changes to make to the default encryption options but yeah this is implemented now :)
