### ISSUE TITLE
Calamares installer request

### ISSUE THREAD

**Issue by seamus-45** [solus-project/os-installer#2]
We can use independent installer [Calamares](https://github.com/calamares/calamares)

**Comment by ikeydoherty** [comment]
We can't. The only real advantage Calamares has over os-installer is the disk partitioning logic - which is provided by KDE. We're no packaging the whole of KDE just for a disk widget, we'll just improve what we have.

(Fwiw os-installer is far older than Calamares so it doesn't count as fragmentation :P)
