### ISSUE TITLE
Bootloader doesn't find valid bootloader location

### ISSUE THREAD

**Issue by Evoolo** [solus-project/os-installer#24]
Hi,
I tried to set up dual boot as described in many tutorials. First set up Windows and afterwards solus with manually setting the partitions. No problem so far, Windows also created the EFI Partition with boot flag, but Solus installer can't find this Partition. Also if i try to create a new one its not working. I have the 2017.01.01 build and an uefi notebook. Normal install without Windows works like a charm.

How can I figure out where the problem is?

**Comment by Evoolo** [comment]
Problem solved. But i needed to insert a second hard disc with an mbr partition table, becaus the Windows disk is GPT. Is that right or is there another solution?

**Comment by cantalupo555** [comment]
Exactly, you need to create MSDOS partition table, you can do this using GParted.
