### ISSUE TITLE
Idea: Use calamares instead of this installer starting with Budgie 11

### ISSUE THREAD

**Issue by dermariusz** [solus-project/os-installer#30]
It could be worth using it in order to avoid duplicating work.

**Comment by ikeydoherty** [comment]
Why? Our installer predates Calamares by a *long* time (several years) - and os-installer is fully featured.
Not sure how I'm duplicating work when I was the first one to do it.

What reasoning do you have for this? And also what does it have to do with Budgie..?

**Comment by dermariusz** [comment]
Ok, I thought calamares would be better as installer but if it isn't I don't mind closing this issue. I only thought the migration of Budgie to Qt would mean that the installer would also migrate to Qt.

**Comment by ikeydoherty** [comment]
Not necessarily no. And if we need to stick a new frontend on it, that's none too difficult
