### ISSUE TITLE
Select the kernel to be installed (LTS or Current)

### ISSUE THREAD

**Issue by kyrios123** [solus-project/os-installer#48]
Ideally, the installer should let the user select which kernel should be installed (instead of having to eventually switch to another kernel after the installation).

**Comment by ikeydoherty** [comment]
Not sure why this is needed? Walk me through the use case here

**Comment by kyrios123** [comment]
You can close this issue if you think it doesn't bring enough added value. I just thought that since Solus offers 2 kernels, it make sense to let people choose the one they want. Perhaps some devices behave better with the `lts` kernel.

Or is the intention to out-phase the lts kernel at some point and Solus has both only to offer a smooth transition ?

**Comment by Girtablulu** [comment]
The only reason for me would the amd gpu users, to have a proper gpu support from the beginning now with 4.15 kernel

**Comment by ikeydoherty** [comment]
Right but we're gonna ship with `linux-current` (4.15) by default now. I think the use case has been eliminated now we identified @kyrios123's original issue

**Comment by adnan449** [comment]
> Not sure why this is needed? Walk me through the use case here

To save time. If a user knows he's going to have to use an LTS kernel, why not give him the option to install it instead? People have their use cases for LTS kernels and that's beyond debate.
