### ISSUE TITLE
Support for eMMC and NVMe SSDs

### ISSUE THREAD

**Issue by Justinzobel** [solus-project/os-installer#5]
Add support for newer internal storage devices present on current gen laptops and desktops.

**Comment by streambinder** [comment]
+1

**Comment by peter-cornelis** [comment]
+1 works for me atm though with my samsung 950 :)
used inxi 2.3.0 for the solus live installer and installed grub 2.0.2 beta 3 in ubuntu

**Comment by Justinzobel** [comment]
@poltertec awesome! Is that an NVMe SSD or an eMMC one?

**Comment by peter-cornelis** [comment]
It's NVMe

**Comment by ikeydoherty** [comment]
Added, will feature in 1.2

**Comment by BamTime** [comment]
Doesn't boot from NVMe drives. Installer freezes while trying to unmount the filesystem

**Comment by ikeydoherty** [comment]
Well it either doesn't boot or it doesn't install @BamTime - it's not both. Those are mutually exclusive concepts.

**Comment by BamTime** [comment]
How can I see all installer output? I'll check then.
