### ISSUE TITLE
Installation fails for vlc and firefox upgrade in solus os 

### ISSUE THREAD

**Issue by rajat12356789** [solus-project/os-installer#51]
every time I install vlc or firefox or just upgrade my system their is this error which states that 'updating manpages database failed'. Also in conjunction to that there is this another error that is 
/usr/bin/mandb: error while loading shared libraries: libgdbm.so.4: cannot open shared object file: No such file or directory
So what I can do  to resolve this error in solus budgie
![screenshot from 2018-02-19 11-02-46](https://user-images.githubusercontent.com/36616363/36363611-738a9c0c-1564-11e8-9487-17ca698c7836.png)

**Comment by ikeydoherty** [comment]
Your system isn't up to date. Please **fully** update it

`sudo eopkg up`

Please note this also isn't an issue with the live installer

**Comment by rajat12356789** [comment]
But this also happens during the update

**Comment by rajat12356789** [comment]
During full upgrade of system this error occurs
