### ISSUE TITLE
Add remove installation media screen when rebooting after installing os

### ISSUE THREAD

**Issue by Jacalz** [solus-project/os-installer#52]
I recently had to help a friend install Ubuntu 16.04 LTS on his computer. When I hit reboot after installing the os and screen came up where it said that I should remove installation media and then hit enter to reboot. 

That is actually a really good thing for noobs like my friend because most computer boots to the usb stick again after rebooting. Thus I think a feature like that would be a really good addition to the Solus installer, in order to make it easier for beginners. :D

**Comment by ikeydoherty** [comment]
I believe this is typically handled by Plymouth, I'm not entirely sure how we'd pull this off in Solus.
If you remove the media while the installer is running, you'll instantly brick the session and won't be able to actually reboot... Maybe if we just change the wording?

**Comment by Jacalz** [comment]
Yeah, something like: Don’t forget to remove the installation media after reboot

**Comment by Jacalz** [comment]
It could say something like:
Remember to remove the installation media after pressing reboot so you boot into the new installation instead of restarting the installation.
