### ISSUE TITLE
Add ability to set partition mount point.

### ISSUE THREAD

**Issue by snwh** [solus-project/os-installer#7]
During the disk config mode, the ability to set a partition's mount point manually is missing. Users may have partitions (such as`/home`) that preserve old data.

**Comment by ikeydoherty** [comment]
Implemented as of `12.0`, will be in Solus 1.2. Thanks for much for all your help @snwh  - it's super appreciated!

**Comment by JuanjoSalvador** [comment]
Sorry for "revive" this issue.

Only swap and /home as mount points, seems not enougth. It is possible to extend this?
