### ISSUE TITLE
[Feature Request] Selection of disk when multiple disks are present

### ISSUE THREAD

**Issue by DataDrake** [solus-project/os-installer#9]
If all someone wants to do is dedicate a secondary or primary disk to Solus while leaving the others alone, currently the only way for them to install is through Manual partitioning. Would be nice if they could just select a whole drive and then do the auto-partitioning.

**Comment by ikeydoherty** [comment]
It already has automatic partitioning, what is the issue?

**Comment by DataDrake** [comment]
So let's say I have this configuration:

/dev/sda - Windows
/dev/sdb - files (ntfs)
/dev/sdc - Empty

If I wanted to auto-partition /dev/sdc and put Solus on that drive. How would I tell the installer to do that? It seems like I would need some way to specify the disk to do this without manual partitioning.

**Comment by ikeydoherty** [comment]
By selecting the drive from the drop-down menu in the installer and telling it to automatically partition it? :)

**Comment by DataDrake** [comment]
does that already exist? sorry if it does
